Bugfix/IJMP-1492 - Handle response
zowe/zowe-client-kotlin-sdk pull request #14
Opened 2024-04-16 15:05 UTC by callbacksin

2024-04-16 20:44 UTC, KUGDev requested changes

2024-04-16 20:44 UTC, KUGDev commented on src/main/kotlin/org/zowe/kotlinsdk/ResponseValidator.kt
> +fun validateResponse(response: Response<*>?, defaultMessage: String = "") {
Docs

2024-04-16 20:44 UTC, KUGDev commented on src/main/kotlin/org/zowe/kotlinsdk/ResponseValidator.kt
> +            throw Exception("code = ${response?.code()}; ${response?.message()}")
HTTP status code = ...; Message: ...

2024-04-16 20:45 UTC, KUGDev commented
Don't forget to update the release candidate version

2024-04-17 11:57 UTC, KUGDev approved these changes

2024-04-17 12:51 UTC, dnlsv approved these changes

2024-04-17 15:10 UTC, ATsikhamirau approved these changes

2024-04-18 19:10 UTC, merged