IJMP-1660-Add-new-TSO-request
zowe/zowe-client-kotlin-sdk pull request #19
Opened 2024-07-19 14:17 UTC by ATsikhamirau

1) added new tso request for z/os versions > 2.3

2024-07-19 15:57 UTC, dnlsv approved these changes

2024-07-24 10:20 UTC, KUGDev requested changes

2024-07-24 10:20 UTC, KUGDev commented on gradle.properties
> +version=0.5.0-rc.9
no need to manually update

2024-07-24 10:20 UTC, KUGDev commented on src/main/kotlin/org/zowe/kotlinsdk/TsoApi.kt
> +  fun executeCommandInTsoAddressSpace(
executeTsoCommand

2024-07-24 10:20 UTC, KUGDev commented on src/main/kotlin/org/zowe/kotlinsdk/TsoResponseEnhanced.kt
> +data class TsoResponseEnhanced(
TsoCmdResponse

2024-07-24 10:20 UTC, KUGDev commented on src/main/kotlin/org/zowe/kotlinsdk/TsoResponseEnhanced.kt
> +data class TsoResult(
TsoCmdResult

2024-07-24 10:20 UTC, KUGDev commented on src/main/kotlin/org/zowe/kotlinsdk/TsoResponseEnhanced.kt
> +data class TsoRequestBody(
TsoCmdRequestBody

2024-07-24 10:20 UTC, KUGDev commented on src/main/kotlin/org/zowe/kotlinsdk/TsoResponseEnhanced.kt
> +enum class CmdState(private val cmdState: String) {
TsoCmdState

2024-07-24 14:49 UTC, KUGDev approved these changes

2024-07-25 09:19 UTC, merged